### PR TITLE
COMP: Fix compile error C2440 in Trial.cpp

### PR DESCRIPTION
**Pull request by NicerNewerCar**
* `Trial.cpp(161,5): error C2440: 'return': cannot convert from 'std::filesystem::path' to 'std::basic_string<char,std::char_traits<char>,std::allocator<char>>'`
* Regression was initially introduced in 6f86beb56b31295b4c30c837a818818b021de4ee
* For future reference: [C2440](https://learn.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/compiler-error-c2440?view=msvc-170&f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(C2440)%26rd%3Dtrue)

### CODE REVIEW

**Comment by jcfr** [comment]
It turns out there there is an implicit conversion from `std::filesystem::path` to `std::basic_string<value_type>` itself equivalent `std::basic_string<char>` only on POSIX system. On windows, implicit conversion returns `std::basic_string<value_type>` with `value_type` being `wchar_t`.

Since `std::basic_string<wchar_t>` is *NOT* equivalent to `std::string` on Windows, this explains the error.


### References

* https://en.cppreference.com/w/cpp/filesystem/path
* https://en.cppreference.com/w/cpp/string
* https://stackoverflow.com/questions/57377349/implicit-conversion-between-stdfilesystempath-and-stdstring-should-it-hap/57377681#57377681
* http://eel.is/c++draft/fs.class.path#fs.path.native.obs


### Illustrations




_Source: http://eel.is/c++draft/fs.class.path#fs.path.native.obs_







_Source: http://eel.is/c++draft/fs.class.path#general-9_




_Source: https://en.cppreference.com/w/cpp/string_

**Review by jcfr — APPROVED** [review]
