### PR TITLE
Fix build error on systems with experimental filesystem lib

### LINKED ISSUE #195: Fix Autoscoper build using GCC 7.3
Following 6f86beb56 (`ENH: Support loading & saving trial config file with relative paths`) introducing the use of the `relative`[^1] function, the `SlicerAutoscoperM` extension build started to fail with the following build error:

```
/work/Preview/S-0-E-b/SlicerAutoscoperM-build/Autoscoper/libautoscoper/src/Trial.cpp: In member function ‘std::string xromm::Trial::toRelativePath(const string&, const string&)’:
/work/Preview/S-0-E-b/SlicerAutoscoperM-build/Autoscoper/libautoscoper/src/Trial.cpp:181:16: error: ‘relative’ is not a member of ‘fs’
     return fs::relative(path, basePath).string();
                ^~~~~~~~
```

[^1]: https://en.cppreference.com/w/cpp/filesystem/relative

Despite of introducing support[^2] for building on system having only `<experimental/filesystem>` (the system where the failure is reported is using `GCC 7.3`), the `relative` function is not available.

[^2]: https://github.com/BrownBiomechanics/Autoscoper/pull/110

This is explained by the fact the support for relative function was introduced later[^3][^4]. 

[^3]: https://open-std.org/JTC1/SC22/WG21/docs/papers/2016/p0219r1.html
[^3]: [^3]: 

Related pull requests:
* https://github.com/BrownBiomechanics/Autoscoper/pull/110
* https://github.com/BrownBiomechanics/Autoscoper/pull/125

### PR DESCRIPTION
**Pull request by NicerNewerCar**
* Fixes build errors on systems using the experimental filesystem library since there is no `relative` function
* See [build errors](https://slicer.cdash.org/viewBuildError.php?buildid=3125027)
* Build was tested using `WSL version: 1.2.5.0` running `Ubuntu 20.04.6` and `gcc 7.5.0`
* I cannot test if my changes work correctly, only that they build. Since programs running on WSL cannot access the GPU. 
* Closes #195

### CODE REVIEW

**Comment by jcfr** [comment]
Running the test from within docker container used to build the extension on Linux :white_check_mark: 

```
$ ctest -R
Test project /work/Tests/Autoscoper-build/Autoscoper-build
    Start 1: TestFileSystemCompat
1/1 Test #1: TestFileSystemCompat .............   Passed    0.00 sec

100% tests passed, 0 tests failed out of 1

Total Test time (real) =   0.01 sec
```

**Comment by jcfr** [comment]
### macOS (computron)

```
% /Users/svc-dashboard/D/Support/CMake-3.22.1.app/Contents/bin/ctest -R                                  
Test project /T/E/SlicerAutoscoperM-build/Autoscoper-build/Autoscoper-build
    Start 1: TestFileSystemCompat
1/1 Test #1: TestFileSystemCompat .............   Passed    0.19 sec

100% tests passed, 0 tests failed out of 1

Total Test time (real) =   0.19 sec
```

**Comment by jcfr** [comment]
### Windows (overload)

```
D:\T\Autoscoper-build\Autoscoper-build>C:\cmake-3.22.1\bin\ctest.exe -C Release -R
Test project D:/T/Autoscoper-build/Autoscoper-build
    Start 1: TestFileSystemCompat
1/1 Test #1: TestFileSystemCompat .............   Passed    0.02 sec

100% tests passed, 0 tests failed out of 1

Total Test time (real) =   0.04 sec
```

**Review by jcfr — APPROVED** [review]
@NicerNewerCar This is ready for integration :rocket:
